<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use function PHPUnit\Framework\isInstanceOf;

class BaseModel extends Model
{
    protected $tablePrefix = '';

    public function getTable()
    {
        return $this->tablePrefix . parent::getTable(); // TODO: Change the autogenerated stub
    }
}
