<?php

namespace App\Models;

use App\Models\Traits\Relations\BelongsToUser;

class Games extends BaseModel
{
    use BelongsToUser;

    protected $fillable = [
        'nonce',
        'amount',
        'result',
    ];

    // TODO: Rebuild function to return appropriate child class
    public function newFromBuilder($attributes = [], $connection = null)
    {
        return parent::newFromBuilder($attributes, $connection); // TODO: Change the autogenerated stub
    }
}
